'use client'

import { useState, useEffect, useRef } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Terminal, Zap, Copy, Check } from 'lucide-react'

const PRESETS = [
  { label: 'Zombie Survival RPG', prompt: 'A zombie survival RPG with base building, crafting, and wave-based enemies. Includes a health system, inventory, and day/night cycle.' },
  { label: 'Space Racing', prompt: 'An anti-gravity racing game set in space with 8 tracks, boost pads, weapons, and a drift mechanic.' },
  { label: 'Fantasy Dungeon', prompt: 'A top-down dungeon crawler with procedurally generated rooms, 5 boss types, loot drops, and a mage character with 4 spells.' },
]

const GENERATION_STEPS = (prompt: string) => [
  { delay: 0,    text: `>> XERON ENGINE v7 — Initializing...` },
  { delay: 400,  text: `>> Parsing prompt: "${prompt.slice(0, 48)}${prompt.length > 48 ? '...' : ''}"` },
  { delay: 900,  text: `>> Routing to Claude Sonnet 4.6 [Pro mode]` },
  { delay: 1400, text: `>> Planning game architecture...` },
  { delay: 1900, text: `   [✓] Terrain system — Baseplate + custom mesh layers` },
  { delay: 2300, text: `   [✓] Spawn system — Dynamic with respawn timers` },
  { delay: 2700, text: `   [✓] Game loop — Wave manager, score tracker` },
  { delay: 3100, text: `   [✓] Lighting — Atmospheric fog + point lights` },
  { delay: 3500, text: `   [✓] Assets — 12 Toolbox models placed` },
  { delay: 3900, text: `>> Generating Lua scripts...` },
  { delay: 4400, text: `   [✓] GameManager.lua — 148 lines` },
  { delay: 4700, text: `   [✓] PlayerController.lua — 94 lines` },
  { delay: 5000, text: `   [✓] EnemyAI.lua — 127 lines` },
  { delay: 5300, text: `   [✓] UIManager.lua — 83 lines` },
  { delay: 5700, text: `>> Compiling export bundle...` },
  { delay: 6200, text: `>> ✦ Generation complete — 6.2s | 50 credits used` },
  { delay: 6500, text: `>> Ready for import in Roblox Studio via XERON Plugin` },
]

const SAMPLE_CODE = `-- GameManager.lua — Generated by XERON Engine
-- Zombie Survival RPG v1.0

local Players = game:GetService("Players")
local RunService = game:GetService("RunService")

local WAVE_INTERVAL = 30
local MAX_ZOMBIES_PER_WAVE = 10

local waveCount = 0
local activeZombies = {}

local function spawnZombie(spawnPos)
  local zombie = game.ServerStorage.Zombies.Basic:Clone()
  zombie.HumanoidRootPart.CFrame = CFrame.new(spawnPos)
  zombie.Parent = workspace
  table.insert(activeZombies, zombie)
  return zombie
end

local function startWave()
  waveCount += 1
  local count = math.min(waveCount * 2, MAX_ZOMBIES_PER_WAVE)
  -- Spawn zombies around map perimeter
  for i = 1, count do
    local angle = (i / count) * math.pi * 2
    local pos = Vector3.new(math.cos(angle) * 80, 3, math.sin(angle) * 80)
    spawnZombie(pos)
  end
end`

export default function DemoTerminal() {
  const [activePreset, setActivePreset] = useState(0)
  const [running, setRunning] = useState(false)
  const [lines, setLines] = useState<string[]>([])
  const [done, setDone] = useState(false)
  const [copied, setCopied] = useState(false)
  const termRef = useRef<HTMLDivElement>(null)
  const timeoutsRef = useRef<ReturnType<typeof setTimeout>[]>([])

  const runDemo = (presetIdx: number) => {
    if (running) return
    setRunning(true)
    setDone(false)
    setLines([])

    const preset = PRESETS[presetIdx]
    const steps = GENERATION_STEPS(preset.prompt)

    timeoutsRef.current.forEach(clearTimeout)
    timeoutsRef.current = []

    steps.forEach(({ delay, text }, i) => {
      const t = setTimeout(() => {
        setLines(prev => [...prev, text])
        if (termRef.current) {
          termRef.current.scrollTop = termRef.current.scrollHeight
        }
        if (i === steps.length - 1) {
          setTimeout(() => { setRunning(false); setDone(true) }, 400)
        }
      }, delay)
      timeoutsRef.current.push(t)
    })
  }

  useEffect(() => {
    // Auto-run first preset after mount
    const t = setTimeout(() => runDemo(0), 800)
    return () => {
      clearTimeout(t)
      timeoutsRef.current.forEach(clearTimeout)
    }
  }, [])

  const handlePreset = (idx: number) => {
    timeoutsRef.current.forEach(clearTimeout)
    setActivePreset(idx)
    setLines([])
    setDone(false)
    setRunning(false)
    setTimeout(() => runDemo(idx), 200)
  }

  const copyCode = () => {
    navigator.clipboard.writeText(SAMPLE_CODE).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  return (
    <div style={{ maxWidth: 860, margin: '0 auto' }}>
      {/* Preset chips */}
      <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap', justifyContent: 'center', marginBottom: 28 }}>
        {PRESETS.map((p, i) => (
          <button
            key={i}
            onClick={() => handlePreset(i)}
            style={{
              padding: '8px 18px',
              borderRadius: 999,
              border: `1px solid ${activePreset === i ? 'rgba(232,188,58,0.6)' : 'rgba(212,160,23,0.2)'}`,
              background: activePreset === i ? 'rgba(212,160,23,0.12)' : 'rgba(212,160,23,0.04)',
              color: activePreset === i ? 'var(--gold-300)' : 'var(--t-3)',
              fontSize: 13,
              fontWeight: activePreset === i ? 600 : 400,
              cursor: 'pointer',
              fontFamily: "'DM Sans', sans-serif",
              transition: 'all 0.2s',
            }}
            onMouseEnter={e => { if (activePreset !== i) (e.currentTarget as HTMLElement).style.borderColor = 'rgba(212,160,23,0.35)' }}
            onMouseLeave={e => { if (activePreset !== i) (e.currentTarget as HTMLElement).style.borderColor = 'rgba(212,160,23,0.2)' }}
          >
            ✦ {p.label}
          </button>
        ))}
      </div>

      {/* Terminal card */}
      <div style={{
        background: 'rgba(3,3,16,0.96)',
        border: '1px solid rgba(212,160,23,0.25)',
        borderRadius: 20,
        overflow: 'hidden',
        boxShadow: '0 0 60px rgba(212,160,23,0.08), 0 40px 80px rgba(0,0,0,0.5)',
      }}>
        {/* Terminal header */}
        <div style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          padding: '12px 20px',
          borderBottom: '1px solid rgba(212,160,23,0.12)',
          background: 'rgba(212,160,23,0.04)',
        }}>
          <div style={{ display: 'flex', gap: 6 }}>
            {['#FF5F57','#FFBD2E','#28C840'].map(c => (
              <div key={c} style={{ width: 12, height: 12, borderRadius: '50%', background: c, opacity: 0.8 }} />
            ))}
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 6, marginLeft: 8 }}>
            <Terminal size={13} color="var(--gold-400)" />
            <span style={{ fontSize: 12, color: 'var(--t-3)', fontFamily: "'JetBrains Mono', monospace" }}>
              xeron-engine — terminal
            </span>
          </div>
          {running && (
            <div style={{ marginLeft: 'auto', display: 'flex', alignItems: 'center', gap: 6 }}>
              <div style={{
                width: 6, height: 6, borderRadius: '50%', background: 'var(--gold-400)',
                animation: 'pulse 1s ease infinite',
              }} />
              <span style={{ fontSize: 11, color: 'var(--gold-400)', fontFamily: "'DM Sans', sans-serif" }}>Generating...</span>
            </div>
          )}
        </div>

        {/* Terminal body */}
        <div
          ref={termRef}
          style={{
            padding: '20px 24px',
            minHeight: 280,
            maxHeight: 320,
            overflowY: 'auto',
            fontFamily: "'JetBrains Mono', monospace",
            fontSize: 13,
            lineHeight: 1.7,
          }}
        >
          <AnimatePresence initial={false}>
            {lines.map((line, i) => (
              <motion.div
                key={i}
                initial={{ opacity: 0, x: -8 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.2 }}
                style={{
                  color: line.startsWith('>>') ? 'var(--gold-300)' : line.startsWith('   [✓]') ? '#4ADE80' : 'var(--t-2)',
                  whiteSpace: 'pre-wrap',
                  marginBottom: 2,
                }}
              >
                {line}
              </motion.div>
            ))}
          </AnimatePresence>
          {running && (
            <motion.span
              animate={{ opacity: [1, 0] }}
              transition={{ duration: 0.7, repeat: Infinity }}
              style={{ color: 'var(--gold-400)', fontFamily: 'monospace' }}
            >
              █
            </motion.span>
          )}
        </div>

        {/* Progress bar */}
        {(running || done) && (
          <div style={{ height: 2, background: 'rgba(212,160,23,0.08)' }}>
            <motion.div
              initial={{ width: '0%' }}
              animate={{ width: done ? '100%' : running ? '85%' : '0%' }}
              transition={{ duration: done ? 0.3 : 6, ease: 'easeOut' }}
              style={{ height: '100%', background: 'linear-gradient(90deg, var(--gold-600), var(--gold-400))' }}
            />
          </div>
        )}

        {/* Code output */}
        <AnimatePresence>
          {done && (
            <motion.div
              initial={{ opacity: 0, height: 0 }}
              animate={{ opacity: 1, height: 'auto' }}
              exit={{ opacity: 0, height: 0 }}
              transition={{ duration: 0.4, ease: 'easeOut' }}
            >
              <div style={{
                borderTop: '1px solid rgba(212,160,23,0.15)',
                padding: '16px 24px',
                background: 'rgba(212,160,23,0.03)',
              }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <Zap size={14} color="var(--gold-400)" />
                    <span style={{ fontSize: 12, color: 'var(--gold-400)', fontWeight: 600, fontFamily: "'DM Sans', sans-serif", textTransform: 'uppercase', letterSpacing: '0.06em' }}>
                      Generated Output — GameManager.lua
                    </span>
                  </div>
                  <button
                    onClick={copyCode}
                    style={{
                      display: 'flex', alignItems: 'center', gap: 6,
                      background: 'rgba(212,160,23,0.08)', border: '1px solid rgba(212,160,23,0.2)',
                      borderRadius: 8, padding: '5px 12px', cursor: 'pointer',
                      color: 'var(--t-3)', fontSize: 12, fontFamily: "'DM Sans', sans-serif",
                      transition: 'all 0.2s',
                    }}
                  >
                    {copied ? <Check size={12} color="#4ADE80" /> : <Copy size={12} />}
                    {copied ? 'Copied!' : 'Copy'}
                  </button>
                </div>
                <div style={{
                  fontFamily: "'JetBrains Mono', monospace",
                  fontSize: 12,
                  lineHeight: 1.75,
                  color: 'var(--t-2)',
                  maxHeight: 220,
                  overflow: 'hidden',
                  position: 'relative',
                }}>
                  <pre style={{ margin: 0, whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                    {SAMPLE_CODE.split('\n').map((line, i) => (
                      <span key={i} style={{
                        color: line.startsWith('--') ? 'var(--t-3)' :
                               line.includes('function') ? '#93C5FD' :
                               line.includes('local') ? '#F9A8D4' :
                               line.includes('"') ? '#86EFAC' :
                               'var(--t-2)',
                      }}>
                        {line}{'\n'}
                      </span>
                    ))}
                  </pre>
                  {/* Fade-out gradient */}
                  <div style={{ position: 'absolute', bottom: 0, left: 0, right: 0, height: 60, background: 'linear-gradient(transparent, rgba(3,3,16,0.96))' }} />
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>

      {/* CTA below */}
      {done && (
        <motion.div
          initial={{ opacity: 0, y: 12 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          style={{ textAlign: 'center', marginTop: 24 }}
        >
          <a href="/register" className="btn-luxury btn-luxury-pulse" style={{ display: 'inline-flex', padding: '14px 32px', fontSize: 15 }}>
            ✦ Try XERON Free
          </a>
        </motion.div>
      )}

      <style>{`
        @keyframes pulse {
          0%, 100% { opacity: 1; transform: scale(1); }
          50% { opacity: 0.5; transform: scale(0.8); }
        }
      `}</style>
    </div>
  )
}
